#ifndef cf_inferno_cor3_declarations_h
#define cf_inferno_cor3_declarations_h

struct cf_inferno_cor3_actor_t;
typedef struct cf_inferno_cor3_actor_t cf_inferno_cor3_actor_t;

struct cf_inferno_cor3_system_t;
typedef struct cf_inferno_cor3_system_t cf_inferno_cor3_system_t;

#endif
