#ifndef cf_x_core_constants_h
#define cf_x_core_constants_h

#define CF_X_CORE_SECONDS_PER_MINUTE 60
#define CF_X_CORE_SECONDS_PER_HOUR 3600
#define CF_X_CORE_SECONDS_PER_DAY 86400

#define CF_X_CORE_BYTES_IN_A_KILOBYTE 1024
#define CF_X_CORE_BYTES_IN_A_MEGABYTE 1048576
#define CF_X_CORE_BYTES_IN_A_GIGABYTE 1073741824

#define CF_X_CORE_MAX_COLOR 2147483647

#define CF_X_CORE_STANDARD_SLEEP_MICROSECONDS 1024

#define CF_X_CORE_WHITESPACE_DELIMITERS " \t\n\r"

#endif
