#ifndef inferno_mcontainer_system_h
#define inferno_mcontainer_system_h

struct inferno_mcontainer_system_t;
typedef struct inferno_mcontainer_system_t inferno_mcontainer_system_t;

inferno_mcontainer_system_t *inferno_mcontainer_system_create();

void inferno_mcontainer_system_destroy(inferno_mcontainer_system_t *system);

#endif
