#ifndef cf_x_psql_system_error_h
#define cf_x_psql_system_error_h

enum cf_x_psql_system_create_error_t {
  cf_x_psql_system_create_error_unknown,
  cf_x_psql_system_create_error_connect_failed,
};
typedef enum cf_x_psql_system_create_error_t cf_x_psql_system_create_error_t;

enum cf_x_psql_system_execute_error_t {
  cf_x_psql_system_execute_error_unknown,
  cf_x_psql_system_execute_error_bad_response,
  cf_x_psql_system_execute_error_empty_query,
  cf_x_psql_system_execute_error_fatal_error,
};
typedef enum cf_x_psql_system_execute_error_t
cf_x_psql_system_execute_error_t;

enum cf_x_psql_system_query_count_error_t {
  cf_x_psql_system_query_count_error_unknown,
  cf_x_psql_system_query_count_error_no_c_column,
};
typedef enum cf_x_psql_system_query_count_error_t
cf_x_psql_system_query_count_error_t;

enum cf_x_psql_system_query_error_t {
  cf_x_psql_system_query_error_unknown,
  cf_x_psql_system_query_error_bad_response,
  cf_x_psql_system_query_error_empty_query,
  cf_x_psql_system_query_error_fatal_error,
};
typedef enum cf_x_psql_system_query_error_t cf_x_psql_system_query_error_t;

enum cf_x_psql_system_vacuum_error_t {
  cf_x_psql_system_vacuum_error_unknown,
};
typedef enum cf_x_psql_system_vacuum_error_t cf_x_psql_system_vacuum_error_t;

#endif
