#ifndef cf_inferno_eos_declarations_h
#define cf_inferno_eos_declarations_h

struct cf_inferno_eos_actor_t;
typedef struct cf_inferno_eos_actor_t cf_inferno_eos_actor_t;

struct cf_inferno_eos_system_t;
typedef struct cf_inferno_eos_system_t cf_inferno_eos_system_t;

#endif
